services:

  db:
    container_name: ${CONTAINER_NAME}
    image: postgres:16-alpine3.20
    restart: always # no=reinicio manual | always=reinicio autom√°tico
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGDATA: /data/postgres
    volumes:
      - '${POSTGRES_DATA_DIR}:/data/postgres'
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
        - '${POSTGRES_PORT}:5432'
